version: '3'

services:
  emqx1:
    image: emqx/emqx:latest
    volumes:
      - ./emqx_auth_http.conf:/opt/emqx/etc/plugins/emqx_auth_http.conf
    environment:
      EMQX_NAME: emqx
      EMQX_HOST: 127.0.0.1
      EMQX_LOADED_PLUGINS: emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_http
    ports:
      - 18083:18083
      - 1883:1883
      - 8883:8883
      - 8083:8083
      - 4369:4369
      - 6000-6100:6000-6100